### ISSUE TITLE
大佬求帮忙，根据自己的数据添加added_tokens.json后，训练时没有去加载added_tokens.json的问题？

### ISSUE THREAD

**Issue by xuelicheng1992** [yongzhuo/Pytorch-NLU#10]

**Comment by xuelicheng1992** [comment]
new_tokens=["443"]
model = "bert-base-chinese"
tokenizer = BertTokenizer.from_pretrained(model, use_fast=True)
model = BertForMaskedLM.from_pretrained(model)
num_added_toks = tokenizer.add_tokens(new_tokens)
model.resize_token_embeddings(len(tokenizer))
tokenizer.save_pretrained("bert-base-chinese")
执行上述代码回在模型下面生成 added_tokens.json文件。
训练时tcData.py文件
将tokenizer = PretrainedTokenizer.from_pretrained(config.pretrained_model_name_or_path)替换为
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained(config.pretrained_model_name_or_path)
或者手动添加方法
开始训练模型时都会报错。

**Comment by xuelicheng1992** [comment]
return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

**Comment by yongzhuo** [comment]
复现该问题，但是没有出错呢，你看看是不是transformers版本，或者是其他问题
![image](https://github.com/yongzhuo/Pytorch-NLU/assets/31341349/ca47cf40-a76d-482b-85e9-af86401ad9f9)
![image](https://github.com/yongzhuo/Pytorch-NLU/assets/31341349/d96b5366-a02c-46f8-a35d-9766ed4412e0)

**Comment by xuelicheng1992** [comment]
找到原因了，我用pip install -i https://pypi.tuna.tsinghua.edu.cn/simple Pytorch-NLU 安装的导致不是最新版代码。

**Comment by xuelicheng1992** [comment]
大佬，谢谢了帮忙排查问题。
