### ISSUE TITLE
想问一下多标签是怎么处理的？跑多标签数据集的时候support值好像总和等于那些只有一个标签的

### ISSUE THREAD

**Issue by chandeler** [yongzhuo/Pytorch-NLU#2]
以给定的school为例，测试集一共有132条，其中多标签的12条，单标签的120条，最后support和为120. 我单步调试看了一下，多标签的样本输入时one hot向量是全零的，想问一下这一步什么原理？

**Comment by yongzhuo** [comment]
已修复, 多标签分隔符参数未更新。
修改 tcRun.py 中的数据预处理函数，
corpus.preprocess(xs_tet, self.config.l2i, max_len=self.config.max_len) 
改为
corpus.preprocess(xs_tet, self.config.l2i, max_len=self.config.max_len, label_sep=self.config.label_sep)
