### ISSUE TITLE
self.do_lower_case 和 self.vocab 没定义，执行报错？！

### ISSUE THREAD

**Issue by Wang-Zhenxing** [yongzhuo/Pytorch-NLU#5]
https://github.com/yongzhuo/Pytorch-NLU/blob/864fb9acc7751fc51abd3d05d24b5a9a7eab7110/pytorch_nlu/pytorch_textclassification/tcData.py#L169

https://github.com/yongzhuo/Pytorch-NLU/blob/864fb9acc7751fc51abd3d05d24b5a9a7eab7110/pytorch_nlu/pytorch_textclassification/tcData.py#L171

这两个类变量在哪定义的？跑代码时报错！

**Comment by yongzhuo** [comment]
感觉没道理呀，用的是哪个模型类型？继承transformers的Tokenizer的

**Comment by Wang-Zhenxing** [comment]
应该是我在[Hugging Face](https://huggingface.co/)下载是预训练模型（albert-base-v1）有问题。
