### ISSUE TITLE
大佬能不能出个零基础的傻瓜式训练测试教程啊，看着有点蒙。

### ISSUE THREAD

**Issue by xuelicheng1992** [yongzhuo/Pytorch-NLU#8]
比如这些预训练模型去哪里下载。

**Comment by yongzhuo** [comment]
> 比如这些预训练模型去哪里下载。

改成默认的repo_id就好，到时候我更新一下

**Comment by xuelicheng1992** [comment]
> > 比如这些预训练模型去哪里下载。
> 
> 改成默认的repo_id就好，到时候我更新一下

期待更新，目前我就弄到bert-base-chinese这个模型。

**Comment by yongzhuo** [comment]
repo_id已更新
